# This file is generated by running tools/generate_ast.py

from tokens import Token

from dataclasses import dataclass


class Expression:
    pass


# -------------------------------------------------------------------------------
@dataclass
class Binary(Expression):
    left: Expression
    operator: Token
    right: Expression


@dataclass
class Grouping(Expression):
    expression: Expression


@dataclass
class Literal(Expression):
    value: str | float | bool


@dataclass
class Unary(Expression):
    operator: Token
    right: Expression
